package lt.vu.usecases.mybatis.model;

public class Location {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LOCATION.ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LOCATION.NAME
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LOCATION.ID
     *
     * @return the value of PUBLIC.LOCATION.ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LOCATION.ID
     *
     * @param id the value for PUBLIC.LOCATION.ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LOCATION.NAME
     *
     * @return the value of PUBLIC.LOCATION.NAME
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LOCATION.NAME
     *
     * @param name the value for PUBLIC.LOCATION.NAME
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}