package lt.vu.usecases.mybatis.model;

public class RecipeProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RECIPE_PRODUCT.RECIPE_ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    private Integer recipeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RECIPE_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RECIPE_PRODUCT.RECIPE_ID
     *
     * @return the value of PUBLIC.RECIPE_PRODUCT.RECIPE_ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    public Integer getRecipeId() {
        return recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RECIPE_PRODUCT.RECIPE_ID
     *
     * @param recipeId the value for PUBLIC.RECIPE_PRODUCT.RECIPE_ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    public void setRecipeId(Integer recipeId) {
        this.recipeId = recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RECIPE_PRODUCT.PRODUCT_ID
     *
     * @return the value of PUBLIC.RECIPE_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RECIPE_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for PUBLIC.RECIPE_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}