package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Location;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    Location selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    List<Location> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    int updateByPrimaryKey(Location record);

    Location selectByName(String name);
}