package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.RecipeProduct;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RecipeProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECIPE_PRODUCT
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    int deleteByPrimaryKey(@Param("recipeId") Integer recipeId, @Param("productId") Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECIPE_PRODUCT
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    int insert(RecipeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECIPE_PRODUCT
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    List<RecipeProduct> selectAll();
}