package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Recipe;

import java.util.List;

public interface RecipeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECIPE
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECIPE
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    int insert(Recipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECIPE
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    Recipe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECIPE
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    List<Recipe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RECIPE
     *
     * @mbg.generated Mon Apr 16 17:11:18 EEST 2018
     */
    int updateByPrimaryKey(Recipe record);
}