CREATE TABLE IF NOT EXISTS LOCATION
(
  NAME CLOB,
  ID   INTEGER IDENTITY PRIMARY KEY NOT NULL
);
CREATE TABLE IF NOT EXISTS PRODUCT
(
  NAME        CLOB,
  CALORIES    INTEGER,
  AMOUNT      INTEGER,
  VALIDUNITL  CLOB,
  ID          INTEGER IDENTITY PRIMARY KEY NOT NULL,
  LOCATION_ID INTEGER,
  CONSTRAINT PRODUCT_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID)
);
CREATE TABLE IF NOT EXISTS RECIPE
(
  TITLE       CLOB,
  ID          INTEGER IDENTITY PRIMARY KEY NOT NULL,
  DESCRIPTION CLOB
);
CREATE TABLE IF NOT EXISTS RECIPE_PRODUCT
(
  RECIPE_ID  INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  CONSTRAINT RECIPE_PRODUCT_PK PRIMARY KEY (RECIPE_ID, PRODUCT_ID),
  CONSTRAINT RECIPE_PRODUCT_RECIPE_ID_FK FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE (ID),
  CONSTRAINT RECIPE_PRODUCT_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);